config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#show'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: [:show]
  resources :events, only: [:new, :create, :show]
  resources :invites, only: [:create, :update]
end

app/models/user.rb
class User < ApplicationRecord
  AcceptedInviteStatusId = InviteStatus.find_or_create_by(status: :accepted).id
  PendingInviteStatusId = InviteStatus.find_or_create_by(status: :pending).id
  DeclinedInviteStatusId = InviteStatus.find_or_create_by(status: :declined).id
  future_event = ->{ where("time > ?", Time.now) }
  has_many :invites, class_name: 'Invite', dependent: :destroy
  has_many :events, through: :invites, source: :event
  has_many :pending_invites, ->{ where(invite_status_id: PendingInviteStatusId) }, class_name: 'Invite'
  has_many :accepted_invites, ->{ where(invite_status_id: AcceptedInviteStatusId) }, class_name: 'Invite'
  has_many :declined_invites, ->{ where(invite_status_id: DeclinedInviteStatusId) }, class_name: 'Invite'
  has_many :pending_events, through: :pending_invites, source: :event
  has_many :accepted_events, through: :accepted_invites, source: :event
  has_many :declined_events, through: :declined_invites, source: :event
  has_many :owned_events, class_name: 'Event', foreign_key: :event_organizer_id, dependent: :destroy
  validates :bio, :username, :profile_photo, presence: :true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6 }
  has_secure_password
  mount_uploader :profile_photo, AvatarUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  before_action :require_logged_out, only: [:new, :create]
  before_action :not_own_profile, only: [:show]
  before_action :require_login, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_as(@user)
      flash[:success] = "Signup Successfull!"
      redirect_to profile_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :bio, :password, :password_confirmation, :photo, :profile_photo)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  private

  def not_own_profile
    if current_user == User.find_by(id: params[:id])
      redirect_to profile_path
    end
  end
end

app/views/users/_user.html.erb
<%= link_to user_path(user.id), class: 'user' do%>
  <%= image_tag(user.profile_photo.url, class: 'avatar-preview') if user.profile_photo.url %>
  <h1><%= user.username %></h1>
<% end %>

app/views/users/_user_info.html.erb
<div class="top-message">
  <%= image_tag(@user.profile_photo.url, class: 'avatar') if @user.profile_photo.url %>
  <div class="separator"></div>
  <h1><%= @user.username%></h1>
  <div class="separator"></div>
  <p class="bio"><%= @user.bio %></p>
</div>
<script>
setTimeout(() => {
  let separators = Array.from(document.querySelectorAll('.separator'));
  separators.forEach(function(separator){
    separator.classList.add("full-width");
  });  
}, 500);
</script>

app/views/users/new.html.erb
<%= render 'layouts/object_errors', object: @user%>
<div class="form-container">
<%= form_for @user, url: signup_path do |f| %>
  <div class="form-title">Sign Up</div>
  <%= f.label 'Username' %>
  <%= f.text_field :username, placeholder: :username %>
  <%= f.label 'password'%>
  <%= f.password_field :password, placeholder: 'Password' %>
  <%= f.label 'password confirmation'%>
  <%= f.password_field :password_confirmation, placeholder: 'Password Confirmation' %>
  <%= f.label 'Profile Photo' %>
  <%= f.file_field :profile_photo %>
  <%= f.label 'Bio'%>
  <%= f.text_area :bio, placeholder: 'Type something about yourself!' %>
  <%= f.submit 'Sign Up'%>
<% end %>
</div>

app/views/users/show.html.erb
<%= render 'users/user_info'%>