config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#show'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: [:show]
  resources :events, only: [:new, :create, :show]
  resources :invites, only: [:create, :update]
end

app/models/event.rb
class Event < ApplicationRecord
  AcceptedInviteStatusId = InviteStatus.find_or_create_by(status: :accepted).id
  PendingInviteStatusId = InviteStatus.find_or_create_by(status: :pending).id
  DeclinedInviteStatusId = InviteStatus.find_or_create_by(status: :declined).id
  scope :past, ->{ where("time < ?", Time.now) }
  scope :future, ->{ where("time > ?", Time.now) }
  belongs_to :event_organizer, class_name: 'User', foreign_key: 'event_organizer_id'
  has_many :invites, dependent: :destroy
  has_many :invited_users, through: :invites, source: 'user'
  has_many :accepted_invites, ->{where(invite_status_id: AcceptedInviteStatusId)}, class_name: 'Invite'
  has_many :attendees, through: :accepted_invites, source: 'user'
  has_many :pending_invites, ->{where(invite_status_id: PendingInviteStatusId)}, class_name: 'Invite'
  has_many :pending_attendees, through: :pending_invites, source: 'user'
  has_many :declined_invites, ->{where(invite_status_id: DeclinedInviteStatusId)}, class_name: 'Invite'
  has_many :non_attendees, through: :declined_invites, source: 'user'
  validates :title, :event_photo, :description, :location, :time, :event_organizer, presence: true
  mount_uploader :event_photo, AvatarUploader
  future_event = ->{ where("time > ?", Time.now) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :require_login, only:[:new, :create, :show]
  before_action :require_exists, only: [:show]
  before_action :require_attendee, only: [:show]
  before_action :require_tab, only: [:show]
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.event_organizer = current_user
    @event.time = selected_date
    if @event.save
      @event.attendees << current_user
      flash[:success] = "Event Created"
      redirect_to event_path(@event.id, tab: :accepted_users)
    else
      render 'new'
    end
  end

  def show
    @event = Event.find_by(id: params[:id])
    if params[:tab] == 'create_invites'
      @display_invite_form = true
      @all_users = User.all - @event.invited_users
    else
      @invited_users = invited_users(@event, params[:tab])
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  private
  def require_attendee
    event = Event.find_by(id: params[:id])
    unless (event &. attendees &. include?(current_user)) || (event.event_organizer == current_user)
      flash[:error] = "You Must be an attendee to view that event!"
      redirect_to profile_path
    end
  end

  def selected_date
    datetime_array = params.require(:datetime).permit(:year, :month, :day, :hour, :minute).values.map(&:to_i)
    DateTime.new(*datetime_array)
  end

  def event_params
    params.require(:event).permit(:title, :event_photo, :description, :location, :time)
  end

  def require_tab
    if params[:tab] == nil
      redirect_to event_path(params[:id], tab: :accepted_users)
    end
  end

  def invited_users(event, tab)
    case tab
    when 'accepted_users'
      event.attendees
    when 'pending_users'
      event.pending_attendees
    when 'declined_users'
      event.non_attendees
    when nil
      event.attendees
    else
      []
    end
  end

  def require_exists
    unless Event.find_by(id: params[:id])
      flash[:error] = "This event does not exist"
      redirect_to profile_path
    end
  end
end

app/views/events/_event.html.erb
<%= render 'events/response_bottons', event: event if request.fullpath == profile_path(tab: :pending_events)%>
<%= link_to event, class: 'event-container' do %>
  <%= image_tag(event.event_photo.url, class: 'avatar') if event.event_photo.url %>
  <div><%= event.location %></div>
  <div><%= event.time %></div>
  <div><%= event.title %></div>
  <div><%= event.description %></div>
<% end %>

app/views/events/_event_users.html.erb
<div class="users">
  <%= render @invited_users %>
</div>

app/views/events/_invite_form.html.erb
<div class="form-container">
<%= form_for(:invites, url: invites_path, method: :post) do |f| %>
  <div class="form-title">Invite Users</div>
  <% @all_users.each do |user| %>
    <%= f.hidden_field :id, :value => "#{@event.id}" %>
      <div class="selection-group">
        <%= f.check_box :users, { multiple: true }, user.id, false %>
        <%= link_to "#{user.username}", user %>
      </div>
    <% end %>
    <%= f.submit 'Invite User(s)' %>
<% end %>
</div>

app/views/events/_invited_users_nav.html.erb
<div class="tab-nav">
  <%= event_tab_link 'Accepted Invites', event_path(event_id, tab: :accepted_users) %>
  <%= event_tab_link "Pending Invites", event_path(event_id, tab: :pending_users) %>
  <%= event_tab_link 'Declined Invites', event_path(event_id, tab: :declined_users) %>
  <%= event_tab_link 'Create Invites', event_path(event_id, tab: :create_invites)%>
</div>

app/views/events/_response_bottons.html.erb
<div class="event-top-options">
  <%= link_to 'Decline' ,invite_path(event.id ,response: :declined) , method: :put, class: :decline %>
  <%= link_to 'Accept' ,invite_path(event.id ,response: :accepted), method: :put, class: :accept %>
</div>

app/views/events/new.html.erb
<%= render 'layouts/object_errors', object: @event%>
<div class="form-container">
  <%= form_for @event do |f| %>
    <div class="form-title">Create Event</div>
    <%= f.label 'Title' %>
    <%= f.text_field :title %>
    <%= f.label 'Description' %>
    <%= f.text_area :description %>
    <%= f.label 'Location' %>
    <%= f.text_field :location %>
    <%= f.label 'Date'%>
    <%= select_datetime Date.today, prefix: :datetime %>
    <%= f.label 'Event Photo'%>
    <%= f.file_field :event_photo %>
    <%= f.submit%>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="top-message">
  <%= image_tag(@event.event_photo.url, class: 'avatar') if @event.event_photo.url %>
  <h2><%= @event.title %></h2>
  <div class="separator"></div>
  <p class="bio"><%= @event.description %></p>
  <div class="separator"></div>
  <div>Event time: <%= @event.time.strftime("%F %T") %></div>
  <div class="separator"></div>
  <div>Event Location: <%= @event.location %></div>
</div>
<%= render 'layouts/attendees_logo' %>
<%= render 'events/invited_users_nav', event_id: @event.id%>
<% if @display_invite_form %>
  <%= render 'invite_form' %>
<% else %>
  <%= render 'event_users' %>
<% end %>
<script>
  setTimeout(() => {
    let separators = Array.from(document.querySelectorAll('.separator'));
    separators.forEach(function(separator){
      separator.classList.add("full-width");
    });  
  }, 500);
</script>