config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'profile', to: 'sessions#show'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: [:show]
  resources :events, only: [:new, :create, :show]
  resources :invites, only: [:create, :update]
end

app/views/layouts/_attendees_logo.html.erb
<div class="event-users-logo">
  <div>Invited Users</div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, string|%>
  <div class="<%="top-message flash-#{type}"%>"><%= string %></div>
<% end %>

app/views/layouts/_logged_in_nav_bar.html.erb
<div class="topnav">
  <%= navbar_link "Log out", logout_path, method: :delete %>
  <%= navbar_link "My Profile", profile_path %>
  <%= navbar_link 'Create Event', new_event_path %>
</div>

app/views/layouts/_logged_out_nav_bar.html.erb
<div class="topnav">
  <%= navbar_link('Login', login_path)%>
  <%= navbar_link('Sign Up', signup_path)%>
</div>

app/views/layouts/_nav_bar.html.erb
<% if logged_in? %>
<%= render 'layouts/logged_in_nav_bar' %>
<% else %>
<%= render 'layouts/logged_out_nav_bar' %>
<% end %>

app/views/layouts/_object_errors.html.erb
<% object.errors.full_messages.each do |message| %>
  <div class="top-message"><%= message %></div>
<% end %>

app/views/layouts/_top_logo.html.erb
<div class="logo-row">
  <% if logged_in? %>
  <%= link_to 'Private Events',profile_path, id: 'logo' %>
  <% else %>
  <%= link_to 'Private Events', login_path, id: 'logo' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/top_logo' %>
    <%= render 'layouts/nav_bar'%>
    <%= render 'layouts/flash' %>
    <%= yield %>
  </body>
</html>